/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.2/userguide/custom_plugins.html
 */

plugins {
    alias(libs.plugins.gradle.publish)
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    `maven-publish`

    alias(libs.plugins.kotlin.jvm)
}

group = "com.github.minigdx"
version = project.properties["version"] ?: "DEV-SNAPSHOT"
if(version == "unspecified") {
    version = "DEV-SNAPSHOT"
}
repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform(libs.kotlin.bom))

    // Use the Kotlin JDK 8 standard library.
    implementation(libs.kotlin.stdlib)

    implementation(libs.kotlin.plugin.mpp)
    implementation(libs.kotlin.plugin.dokka)
    implementation(libs.ktlint.plugin)

    implementation(platform(libs.jdoctor.bom))
    implementation(libs.jdoctor.core)
    implementation(libs.jdoctor.utils)

    // Use the Kotlin test library.
    testImplementation(libs.bundles.test)
}

gradlePlugin {
    // Define the plugin
    val developer by plugins.creating {
        id = "com.github.minigdx.gradle.plugin.developer"
        implementationClass = "com.github.minigdx.gradle.plugin.MiniGdxDeveloperPlugin"
        displayName = "MiniGDX Developer plugin"
        description = """Configure MiniGDX libs with a common set of configuration and tasks.
                | The usage is mainly for MiniGDX contributors.
            """.trimMargin()
    }

    val mpp by plugins.creating {
        id = "com.github.minigdx.gradle.plugin.developer.mpp"
        implementationClass = "com.github.minigdx.gradle.plugin.MiniGdxKotlinMppPlugin"
        displayName = "MiniGDX Kotlin JVM Developer plugin"
        description = """Configure MiniGDX libs to build for the JVM only.
                | The usage is mainly for MiniGDX contributors.
            """.trimMargin()
    }

    val jvm by plugins.creating {
        id = "com.github.minigdx.gradle.plugin.developer.jvm"
        implementationClass = "com.github.minigdx.gradle.plugin.MiniGdxKotlinJvmPlugin"
        displayName = "MiniGDX Kotlin Multiplatform Developer plugin"
        description = """Configure MiniGDX libs to build for different platforms.
                | The usage is mainly for MiniGDX contributors.
            """.trimMargin()
    }
}

pluginBundle {
    website = "https://github.com/minigdx/minigdx-developer-gradle-plugin"
    vcsUrl = "https://github.com/minigdx/minigdx-developer-gradle-plugin"

    tags = listOf("minigdx", "developer")

    pluginTags = mapOf(
        "jvm" to listOf("kotlin", "jvm"),
        "mpp" to listOf("kotlin", "jvm", "mpp", "ios", "js", "android", "native")
    )
}

val compileKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks
compileKotlin.kotlinOptions.jvmTarget = "1.8"

// Add a source set for the functional test suite
val functionalTestSourceSet = sourceSets.create("functionalTest") {
}

gradlePlugin.testSourceSets(functionalTestSourceSet)
configurations["functionalTestImplementation"].extendsFrom(configurations["testImplementation"])

// Add a task to run the functional tests
val functionalTest by tasks.registering(Test::class) {
    testClassesDirs = functionalTestSourceSet.output.classesDirs
    classpath = functionalTestSourceSet.runtimeClasspath
}

tasks.check {
    // Run the functional tests as part of `check`
    dependsOn(functionalTest)
}

// Ensure "org.gradle.jvm.version" is set to "8" in Gradle metadata.
tasks.withType<JavaCompile> {
    sourceCompatibility = JavaVersion.VERSION_1_8.toString()
    targetCompatibility = JavaVersion.VERSION_1_8.toString()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

kotlin {
    jvmToolchain {
        (this as JavaToolchainSpec).languageVersion.set(JavaLanguageVersion.of(11))
    }
}
