/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.minigdx.gradle.plugin

import org.gradle.api.Project
import org.gradle.internal.extensions.core.extra
import org.gradle.testfixtures.ProjectBuilder
import org.jetbrains.kotlin.gradle.plugin.extraProperties
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.github.minigdx.gradle.plugin.greeting' plugin.
 */
class MiniGdxDeveloperPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder
            .builder()
            .build()
            .also {
                it.extraProperties.set("minigdx.dokka.skip", "true")
            }
        project.plugins.apply("com.github.minigdx.gradle.plugin.developer")

        // Verify the result
        assertNotNull(project.tasks.findByName("createGithubWorkflows"))
        assertNotNull(project.tasks.findByName("createMakefile"))
    }
}
