/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.minigdx.gradle.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import java.io.File

/**
 * Plugin for developers of MiniGDX project.
 *
 * It configures plugins used in the project that are commons to all projects
 * like the publication, kotlin version, ...
 */
class MiniGdxDeveloperGradlePlugin : Plugin<Project> {

    private val classLoader = MiniGdxDeveloperGradlePlugin::class.java.classLoader

    override fun apply(project: Project) {
        configureProjectVersionAndGroupId(project)
        configureProjectRepository(project)
        configureKotlinMultiplatform(project)
        // TODO: Configure Publication

        // TODO: Configure tasks for local deploy, ...

        // TODO: Configure linter

        configureGithubWorkflow(project)
    }

    private fun configureProjectVersionAndGroupId(project: Project) {
        var version = project.properties["version"] ?: DEFAULT_VERSION

        if (version == "unspecified") {
            version = DEFAULT_VERSION
        }

        project.version = version
        project.group = "com.github.minigdx"
    }

    private fun configureProjectRepository(project: Project) {
        project.repositories.mavenCentral()
        project.repositories.google()
        project.repositories.mavenLocal()
    }

    private fun configureKotlinMultiplatform(project: Project) {
        project.apply { it.plugin("org.jetbrains.kotlin.multiplatform") }
        project.extensions.configure<KotlinMultiplatformExtension>("kotlin") { mpp ->
            mpp.js {
                this.useCommonJs()
                this.browser {
                    this.webpackTask {
                        this.compilation.kotlinOptions {
                            this.sourceMap = true
                            this.sourceMapEmbedSources = "always"
                        }
                    }
                }
                this.nodejs
            }

            mpp.jvm {
                this.compilations.getByName("main").kotlinOptions.jvmTarget = "1.8"
                this.compilations.getByName("test").kotlinOptions.jvmTarget = "1.8"
            }

            project.plugins.withId("com.android.library") {
                mpp.android {
                    publishLibraryVariants("release", "debug")
                }
            }

            mpp.mingwX64 {
                binaries {
                    staticLib { }
                    sharedLib { }
                }
            }
            mpp.linuxX64 {
                binaries {
                    staticLib { }
                    sharedLib { }
                }

            }
            mpp.ios {
                binaries {
                    staticLib { }
                    sharedLib { }
                }
            }
            mpp.macosX64 {
                binaries {
                    staticLib { }
                    sharedLib { }
                }
            }

            mpp.sourceSets.apply {
                getByName("commonMain") {
                    it.dependencies {
                        implementation(kotlin("stdlib-common"))
                    }
                }

                getByName("commonTest") {
                    it.dependencies {
                        implementation(kotlin("test-common"))
                        implementation(kotlin("test-annotations-common"))
                    }
                }

                getByName("jsMain") {
                    it.dependencies {
                        implementation(kotlin("stdlib-js"))
                    }
                }

                getByName("jsTest") {
                    it.dependencies {
                        implementation(kotlin("test-js"))
                    }
                }

                getByName("jvmMain") {
                    it.dependencies {
                        implementation(kotlin("stdlib-jdk8"))
                    }
                }

                getByName("jvmTest") {
                    it.dependencies {
                        implementation(kotlin("test-junit"))
                    }
                }

            }
        }
    }

    private fun configureGithubWorkflow(project: Project) {
        fun copy(filename: String, target: File) {
            val content = classLoader.getResourceAsStream("github/workflow/$filename")!!
            target.resolve(filename).apply {
                createNewFile()
                writeBytes(content.readBytes())
            }
        }
        project.rootProject.tasks.register("createGithubWorkflows") {
            it.group = "minigdx-dev"
            it.doLast {
                val target = it.project.mkdir(".github/workflows")
                copy("build.yml", target)
                copy("publish-release.yml", target)
            }
        }
    }

    companion object {

        private const val DEFAULT_VERSION = "DEV-SNAPSHOT"
    }
}
